#!/bin/bash

export PROJECT=daq-module
export PRJROOT=$PWD/${PROJECT}
export TARGET=powerpc-unknown-linux
export HOST=i686-cross-linux-gnu
export PREFIX=${PRJROOT}/tools
export TARGET=${PREFIX}/${TARGET}
export PATH=${PREFIX}/bin:${PATH}

